### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by NoFoolLikeOne** [NoFoolLikeOne/EDMC-Highway-N#2]
I need to get the query to run in the background somehow so the front end doesn't stop responding.

Making multiple calls would be faster than making a single call in a neutron dense area but it would be worse in a neutron poor area. 

Perhaps what we need is a density function.

The first jump does a long range query then works out the neutron density.

If there are lots of neutron stars in the region then subsequent executions use short range queries.
If short range stops working then we go back to long range and recalculate density. 

Or maybe if I have one at 20y and one at 50ly and ship jumps 30 then I am guaranteed to find as start between 0 and 80ly within the current data set . So don't have to fetch 200 Ly

**Comment by NoFoolLikeOne** [comment]
j = distance jumped
d(n1) = distance to first neutron star
d(n2) = distance to next neutron star
r = Lower Range 
r2 = Upper Range
M = 200 Maximum range

As we are jumping in a random direction the distance to the next star is d +/- j

```
If d(n1)+ j >=M-j then
  # There might be closer stars  
  r = d(n1)-j 
  if ( r < 0 then )r = 0
  R = 200

elsif d(n1)+ j <= d(n2)-j  then
    #there is no overlap between first and next star so the first star is always closest
    get_d(n1) # This is a faster query from EDSM

elseif d(n2)+j < M-j then
     #we know d(n2) and d(n1) overlap if we got this far but we could have a closer star
  r = d(n1)-j 
  if ( r < 0 then )r = 0
  R = d(n1)+j

else 
   r = d(n1)-j 
   R = d(n1)+j
```

When calling the getsphere command then execute two commands the second conditional on the first
  r= d(n1)-j, R = (n1)+j  
  r = d(n1)+j, R = d(n2)+j

**Comment by NoFoolLikeOne** [comment]
If I can get the coordinates of the current star

distance between two stars = sqrt( (x1-x2)^2 + (y1-y2)^2 + (z1-xz)^2)

**Comment by NoFoolLikeOne** [comment]
Calling at the start of the FSD Jump means that the EDSM sphere request will happen  during the dead time in the middle of the jump. But it also means that that the coordinates are unavailable. 

Given that in some situations we know the last nearest neutron is still the nearest we want to use the coordinates to calculate the distance.

We could use the EDSM API to get the coordinates. at the start of the jump but for undiscovered systems the coordinates are unknown until we get the second Jump event.

```
startJump event
get coordinates from EDSM
if coordinate found
   findNextStar
else
  set NotFound
end



FSDJump event
if NotFound
  wait for EDSM to be updated
  findNextStar
end
```

When we want to find tbe next star we know the coordinates so we can calculate the distance to the last two nearest neutrons in some cases we wont need to hit up EDSM again because we know that no new Neutron stars can have come into range.

As we know the distance to all the neutron stars we have found so far we dont need the range of the call to cover them. so we only need one call with Range 150-200 but this means we need to keep distances to all neutron stars within 200ly of the last jump.

Would it be feasible to keep coordinates of every neutron star since the start of the session?

**Comment by NoFoolLikeOne** [comment]
@AnthorNet I've made some changes to the code so that I don't have to hit EDSM quite so much. In the first 800ly around the bubble it won't need to talk to EDSM at all.

Anywhere outside the bubble, it will hit a local cache of Neutron stars first and then in the background fire off a query to get a 200ly sphere in case new Neutron starts have been found since the cache was made. I'll add in some code to reduce the minRange based on the length of the last jump.

The results of the edsm query will be stored locally so they can be used for the initial search. In this way the CMDR will build up a database as they travel. 

I was wondering if it would make sense to create caches for SagA and Colonia too but I don't know how thoroughly they will have been explored or out to how far. 

Any thoughts?

**Comment by NoFoolLikeOne** [comment]
I can determine max range.

I do my preliminary scan through the cache. 
I now have a nearest star. I only need to scan far enough ahead to see if there is a closer star. 

d1 = preliminary distance
j = size of jump
minRange = 200-j
maxRange = d1

if d1 < minRange then I don't need to hit EDSM  

However if EDSM doesn't have all stars at the time I created the cache then I will never add any new stars to the cache.  So really minRange has to be 0 when I am in uncharted space. 

I guess there is no way of knowing for sure when EDSM is complete but I could try and distinguish between high traffic and low traffic areas and adjust the range accordingly.

**Comment by AnthorNet** [comment]
Have you tried using minDate and maxDate? Don't have doc in mind right now
But you could reduce the set of systems from where your cache was last filled.

**Comment by NoFoolLikeOne** [comment]
Thanks Anthor, That's neat. Its not documented in the sphere-systems API but it clearly works and quickly returns results. 

https://www.edsm.net/api-v1/sphere-systems?systemName=Colonia&minRadius=0&radius=200&showPrimaryStar=1&filterPrimaryStar=N&showCoordinates=1&startDateTime=2017-09-07%2000:00:00

Brings back a single star.
Eol Prou ZT-R d4-996

But that system was found well before that. 

That system was first discovered for EDSM by ExplodingLlama on Aug 29, 2016, 12:17:09 AM.
2 ships passed through Eol Prou ZT-R d4-996 space, including 1 ship in the last 7 days.
1 ship passed through Eol Prou ZT-R d4-996 space in the last 24 hours. 

I'm not sure how useful it would be other than maybe to use a rudimentary traffic report about the area i'm currently in as my cache is based on a series of overlapping spheres taken at different times.

I'll give it some thought as it might come in handy.

**Comment by AnthorNet** [comment]
It might just be that one if the system field was updated, may be a slight correction of coordinates or anything else.

All parameters of the 'system' API should be available to every systems endpoint.

**Comment by NoFoolLikeOne** [comment]
Thanks @AnthorNet I really appreciate you taking the time. Having someone to bounce ideas off helps me come up with other ideas.

Now that I think of it, maybe I should simply do a count of Neutron stars within 25ly of the current position and if I have plenty then not bother with the EDSM query. I could even calculate the number within a cone along the direction of travel if I wanted to be extra clever.  

I was wondering if any of the traffic report info was available in the API? So I could jump, then get the traffic report of the current system and if it was very busy and I had plenty of neutron stars in the cache already then I could avoid making a call to get the sphere. 

I think a traffic report would be really useful to have in EDMC because when you jump into a system you can see if you are likely to encounter other commanders.

**Comment by AnthorNet** [comment]
Not available, but feel free to raise an issue :)

**Comment by NoFoolLikeOne** [comment]
Ok thanks. I'll  most likely do that then :)

**Comment by NoFoolLikeOne** [comment]
Been using this for some time now and performance seems pretty good especially as the lookup happens in the background
